##
# (c) 2021 - Cloud Ops Works LLC - https://cloudops.works/
#            On GitHub: https://github.com/cloudopsworks
#            Distributed Under Apache v2.0 License
#
name: Create Release

on:
  workflow_call:
    inputs:
      release-tag:
        required: true
        type: string
      files-globs:
        required: false
        default: |
            target/*.zip
            target/*.tgz
        type: string
    secrets:
      token:
        required: true

jobs:
  create:
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          name: all-artifacts

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.token }}
          body_path: CHANGELOG.md
          name: "Release v${{ inputs.release-tag }}"
          tag_name: v${{ inputs.release-tag }}
          files: ${{ inputs.files-globs }}
          